In [1]:
# Library
from urllib.request import urlopen
import pandas as pd
from bs4 import BeautifulSoup
import webbrowser
import numpy as np
import re

In [2]:
# url connecting
url ='https://lab.donutz.co/krx/products'
resultXML = urlopen(url)
result = resultXML.read()
soup = BeautifulSoup(result,'html.parser')
soup_string = str(soup)
regex = re.compile(r'(\d{6})')
code = regex.findall(soup_string)
code = '005930'
start_date = '20170101'
end_date = '20191231'

In [3]:
# Crawling
url ='https://lab.donutz.co/krx/products/' + code + '?sdate=' + start_date + '&edate=' + end_date
resultXML = urlopen(url)
result = resultXML.read()
soup = BeautifulSoup(result,'html.parser')
soup_string = str(soup)

In [4]:
# 특수문자 제거
def clean(data):
    text = re.sub('[a-zA-Z-=+#/\?^$@*\"※~&%ㆍ!_』:\\‘|\(\)\[\]\<\>`\'{}…》]', '', data)
    return text
text = re.split('[,]+',clean(soup_string))
information = []
for i in text:
    information.append(i)

In [5]:
# 데이터프레임으로 변환
data = pd.DataFrame(np.array(information).reshape(-1,15))
data.columns = ['date','open','high','low','close','trading_volume',\
                'score','index','probability','l1','l2','l3','l4','lgap','lrate']

In [6]:
# Data to Float
data['open'] = data['open'].apply(lambda x : np.float(x))
data['high'] = data['high'].apply(lambda x : np.float(x))
data['low'] = data['low'].apply(lambda x : np.float(x))
data['close'] = data['close'].apply(lambda x : np.float(x))
data['trading_volume'] = data['trading_volume'].apply(lambda x : np.float(x))
data['score'] = data['score'].apply(lambda x : np.float(x))
data['index'] = data['index'].apply(lambda x : np.float(x))
data['probability'] = data['probability'].apply(lambda x : np.float(x))
data['l1'] = data['l1'].apply(lambda x : np.float(x))
data['l2'] = data['l2'].apply(lambda x : np.float(x))
data['l3'] = data['l3'].apply(lambda x : np.float(x))
data['l4'] = data['l4'].apply(lambda x : np.float(x))
data['lgap'] = data['lgap'].apply(lambda x : np.float(x))
data['lrate'] = data['lrate'].apply(lambda x : np.float(x))

In [7]:
# L1 ~ L4 Line 정리
data['l1'] = data['l1'] - 100000
data['l2'] = data['l2'] - 200000
data['l3'] = data['l3'] - 300000
data['l4'] = data['l4'] - 400000

In [8]:
# Zone 생성
data['Zone'] = 100 * (data['close'] - data['close'].shift(1)) / data['close'].shift(1)

In [9]:
data

,date,open,high,low,close,trading_volume,score,index,probability,l1,l2,l3,l4,lgap,lrate,Zone
0,20170102,35980.0,36240.0,35880.0,36100.0,4650600.0,8.726027,1.333333,44.000000,36350.0,36170.0,35990.0,35810.0,540.0,1.0,NaN
1,20170103,36280.0,36620.0,36020.0,36480.0,7357650.0,8.726027,1.333333,44.000000,36850.0,36550.0,36250.0,35950.0,900.0,2.0,1.052632
2,20170104,36500.0,36520.0,36100.0,36160.0,7971750.0,8.726027,1.333333,44.000000,36550.0,36340.0,36130.0,35920.0,630.0,2.0,-0.877193
3,20170105,36060.0,36060.0,35540.0,35560.0,10967450.0,8.342105,1.333333,44.000000,36070.0,35810.0,35550.0,35290.0,780.0,2.0,-1.659292
4,20170106,36180.0,36440.0,36040.0,36200.0,8880950.0,13260.000000,25.000000,79.840256,36520.0,36320.0,36120.0,35920.0,600.0,2.0,1.799775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,20191223,56100.0,56400.0,55100.0,55500.0,9476863.0,19350.000000,20.000000,79.750623,56600.0,55950.0,55300.0,54650.0,1950.0,4.0,-0.892857
729,20191224,55600.0,55700.0,54800.0,55000.0,9146734.0,19350.000000,20.000000,79.750623,55800.0,55350.0,54900.0,54450.0,1350.0,2.0,-0.900901
730,20191226,54700.0,55400.0,54400.0,55400.0,9503018.0,19800.000000,21.000000,79.773756,55900.0,55400.0,54900.0,54400.0,1500.0,3.0,0.727273
731,20191227,55700.0,56900.0,55500.0,56500.0,12261723.0,19900.000000,22.000000,79.793814,57400.0,56700.0,56000.0,55300.0,2100.0,4.0,1.985560
732,20191230,56200.0,56600.0,55700.0,55800.0,8325542.0,19400.000000,20.000000,79.750623,56650.0,56200.0,55750.0,55300.0,1350.0,2.0,-1.238938